### ISSUE TITLE
How can I get address data after I set it into Gogle Map custm field?

### ISSUE THREAD

**Issue by sailorsamoor** [gyrus/WordPress-Developers-Custom-Fields#41]
Hello.
I use Google Maps field. When I'm setting a marker on a Google Map,  I input its address - Street, City etc.  into form field. How can I use its address further - could I get the address into some variable?

Best regards.

**Comment by gyrus** [comment]
At present, I'm still supporting this plugin in terms of fixing bugs - a number of my client sites still use it. However, it's no longer being actively developed - I use CMB2 for new projects. This sounds like a request for a new feature, so I won't address it, sorry. Please let me know if I've misunderstood and you're actually describing a bug.

**Comment by sailorsamoor** [comment]
Thank you for the plugin). No, it is not an error, it was been a question. All works fine, thank you again.

**Comment by gyrus** [comment]
OK, glad the plugin is of use :)
